### ISSUE TITLE
SavePointsToPLY creates faces

### ISSUE THREAD

**Issue by martinruenz** [facebookresearch/DeepSDF#17]
When exporting testing point clouds via `SampleVisibleMeshSurface`, the function `SavePointsToPLY` generates faces, which I think is not the intended behaviour. Also, there are some mislabellings for the CLI11 options (see `-s`).

I can send a pull request to fix these minor issues, if you want to.

**Comment by tschmidt23** [comment]
The -s flag is used for the number of samples is just because -n was already taken.

As for the faces, generating those actually is intended, just because on at least one system we tested we were unable to load .ply files using trimesh which contained only points (no faces). It seems trimesh was deleting unreferenced vertices, which was all of them, so the SavePointsToPLY function adds one face referencing each vert. This is annoying for visualization because the connectivity is random (e.g. in meshlab you'll want to render only the points). There is probably a better fix, but for now this avoids having the points deleted and the evaluation code ignores the faces anyway.

**Comment by martinruenz** [comment]
I see, thanks for the clarification!
